# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Ramer-Douglas-Peucker
#'
#' The Ramer-Douglas-Peucker algorithm for reducing the number of points on a curve.
#'
#' @param x The `x` values of the curve.
#' @param y The `y` values of the curve.
#' @param epsilon The threshold for filtering outliers from the simplified curve.
#'
#' @return A `data.frame` with `x` and `y` values of the simplified curve.
#'
#' @export
#'
RamerDouglasPeucker <- function(x, y, epsilon) {
    .Call(`_RDP_RamerDouglasPeucker`, x, y, epsilon)
}

