# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Ramer-Douglas-Peucker
#'
#' The Ramer-Douglas-Peucker algorithm for reducing the number of points on a curve.
#'
#' @param x The `x` values
#' @param y The `y` values
#' @param epsilon The
#'
#' @return The `x` and `y` values.
#'
#' @export
#'
RDP <- function(x, y, epsilon) {
    .Call(`_RDP_RDP`, x, y, epsilon)
}

